### PR TITLE
use registry api directly instead of using the docker cli

### PR DESCRIPTION
**Pull request by willforde**
This pull request changes from using the Docker CLI to using the Docker registry API directly.

I had an issue where this action would not work for me as I was using a buildkit registry cache.
And the Docker CLI would fail with error, `manifest unknown`, when attempting to read the manifest for the buildcache. But it worked perfectly when using the API.

### CODE REVIEW

**Comment by Chizkiyahu** [comment]
this change have dependency of python-dxf 
and I prefer to minimize dependencies

**Comment by mering** [comment]
> this change have dependency of python-dxf and I prefer to minimize dependencies

@willforde would it be possible to use `requests` which is already used instead of `python-dxf`?

**Comment by Chizkiyahu** [comment]
> @Chizkiyahu Docker is a huge dependency as well, which gets removed in this PR.

I don’t understand current main dependency is only requests

**Comment by Chizkiyahu** [comment]
> > @Chizkiyahu Docker is a huge dependency as well, which gets removed in this PR.
> 
> I don’t understand current main dependency is only requests

@mering 
After second read 
The needs for docker in the env is not a problem for me because without docker I can’t build the image in the first place 
I can’t remove docker all together from my tool chain and still build docker images 

so the assumption for everyone using this action is that docker and docker action is ok to use

**Comment by Chizkiyahu** [comment]
@willforde 
Did you try with except_untagged_multiplatform true 
If not please try to create an issue  with public example of creating images 
And I will try to solve the problem

**Pull request closed without merging**
