### PR TITLE
Add output with the number of deleted package versions

### PR DESCRIPTION
**Pull request by mering**
Use this output also to improve tests

### CODE REVIEW

**Comment by Chizkiyahu** [comment]
@mering 
Is fail in https://github.com/Chizkiyahu/delete-untagged-ghcr-action/actions/runs/6785873604
I fix in https://github.com/Chizkiyahu/delete-untagged-ghcr-action/commit/22e65b443e7bec4eef242319005018e2fdcf198f
still fails in https://github.com/Chizkiyahu/delete-untagged-ghcr-action/actions/runs/6786034181

**Comment by mering** [comment]
Sorry, rebase error after I had to make changes in #33 (I only tested it with the original version of it). Should be fixed now.

**Comment by mering** [comment]
Could you please have another look?

**Comment by Chizkiyahu** [comment]
> Could you please have another look?
is fail
https://github.com/Chizkiyahu/delete-untagged-ghcr-action/actions/runs/6810990584/job/18520406549

**Comment by mering** [comment]
It seems that it is not possible to use this action to clean up in the beginning as it fails when there are no packages (which is the usual step).

I tested it on my repo and the latest version works there.

**Comment by Chizkiyahu** [comment]
You can add param ignore pkg not exist 
And ignore this error  in the code

**Comment by mering** [comment]
> You can add param ignore pkg not exist And ignore this error in the code

Let's do this in a separate PR. The functionality of this PR in itself is valuable as is.

**Comment by Chizkiyahu** [comment]
@mering 
is not a bug in your code 
https://github.com/orgs/community/discussions/75302

**Comment by Chizkiyahu** [comment]
@mering 
merged in https://github.com/Chizkiyahu/delete-untagged-ghcr-action/pull/36

**Pull request closed without merging**
